name: lutris
confinement: strict
base: core22
grade: stable
adopt-info: lutris

architectures:
  - build-on: amd64
  - build-on: i386

package-repositories:
  - type: apt
    url: http://archive.ubuntu.com/ubuntu/
    suites: [jammy]
    components: [main, universe]
    architectures: [amd64, i386]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com

  - type: apt
    url: http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu
    suites: [jammy]
    components: [main]
    architectures: [amd64, i386]
    key-id: 5ABCE68FF4633EA42E219156957D2708A03A4626
    key-server: keyserver.ubuntu.com

parts:
  ld-precache:
    after:
      - lutris
      - lutris-runtime
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-utils-library.git
    source-subdir: snapcraft-assets/ld-precache

  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      dpkg --add-architecture i386
      apt update

  lutris:
    after: [enable-i386]
    plugin: python
    source: .
    parse-info: [share/metainfo/net.lutris.Lutris.metainfo.xml]
    stage-packages:
      - libmagic1
    override-pull: |
      snapcraftctl pull
      sed -i 's|Icon=.*|Icon=${SNAP}/share/icons/hicolor/scalable/apps/lutris.svg|' share/applications/net.lutris.Lutris.desktop
    # Reverse the sed the default build script does because it sets it to the install part python3 which doesn't exist
    # when it runs
    #
    # This is only necessary because we need to override the fact that the Gnome SDK coerces the snap environment to make its
    # Python the build one, which gets discarded post-build. So the chain here is
    #
    # Gnome extension python rips control from snapcraft python -> we coerce it back to snapcraft python -> we tell it to use the
    # snap Python in the final run environment.
    override-build: |
      craftctl default
      /root/parts/lutris/install/bin/python3 setup.py install
      exit 1
      find /root/parts/lutris/install -type f -executable | xargs sed -i '1 s|#\!/usr/bin/env python3|^#\!/root/parts/lutris/install/bin/python3.*$|'
    build-environment:
      - PYTHONUSERBASE: $CRAFT_PART_INSTALL

  lutris-runtime:
    after: [enable-i386]
    plugin: nil
    override-pull: |
      snapcraftctl pull
      dpkg --add-architecture i386
      apt update
    stage-packages:
      - cabextract
      - curl
      - fluid-soundfont-gs
      - libgnutls30
      - libxrandr2
      - pciutils
      - p7zip
      - psmisc
      - unzip
      - wine
      - xz-utils
      #32 bit
      - lib32gcc-s1
      - libc6-i386
      - libglu1-mesa:i386
      - libglvnd0:i386
      - libglx-mesa0:i386
      - libgnutls30:i386
      - libvulkan1:i386
      - libx11-6:i386
      # - x11-xserver-utils:i386
    stage:
      - -lib/ld-linux.so.2
      - -usr/bin/cpp-7
      - -usr/lib/*/libjavascript*
      - -usr/lib/*/libwebkit*
      - -usr/share/doc/cpp/README.Debian
      - -usr/share/man/man1/cpp-7.1.gz
    build-attributes:
      - no-patchelf

layout:
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache

slots:
  dbus-lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris

environment:
  HOME: $SNAP_USER_COMMON

apps:
  lutris:
    command: bin/lutris -d
    extensions: [gnome]
    desktop: share/applications/net.lutris.Lutris.desktop
    common-id: net.lutris.Lutris
    plugs:
      - audio-playback
      - browser-support
      - daemon-notify
      - desktop
      - desktop-legacy
      - gsettings
      - hardware-observe
      - home
      - io-ports-control
      - joystick
      - kvm
      - libvirt
      - mount-observe
      - network
      - network-bind
      - network-manager
      - opengl
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - unity7
      - wayland
      - x11
    slots:
      - dbus-lutris
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH
      PATH: $SNAP/usr/lib/wine:$PATH
      WINEDLLPATH: $SNAP/usr/lib/x86_64-linux-gnu/wine/
      MAGIC: $SNAP/usr/share/misc/magic.mgc
      # From the gnome extension hacks
      LIBGL_DRIVERS_PATH: $LIBGL_DRIVERS_PATH:$SNAP/usr/lib/i386-linux-gnu/dri
      LD_LIBRARY_PATH: $SNAP/usr/lib/i386-linux-gnu:$SNAP/lib/i386-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$LIBGL_DRIVERS_PATH"
      LIBVA_DRIVERS_PATH: $SNAP/usr/lib/i386-linux-gnu/dri
