name: lutris
confinement: strict
base: core22
grade: stable
adopt-info: lutris

lint:
  # Snapcraft's `ldd` lint can't handle 32-bit things,
  # So just make it quiet and also make builds a surprising amount faster
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**
        - opt/wine-stable/lib/wine/i386-unix/**
        - opt/wine-stable/bin/wine
        - usr/bin/perl5.34-i386-linux-gnu

architectures:
  - build-on: amd64

package-repositories:
  - type: apt
    url: http://archive.ubuntu.com/ubuntu/
    suites: [jammy]
    components: [main, universe]
    architectures: [amd64, i386]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    key-server: keyserver.ubuntu.com
  - type: apt
    url: http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu
    suites: [jammy]
    components: [main]
    architectures: [amd64, i386]
    key-id: 5ABCE68FF4633EA42E219156957D2708A03A4626
    key-server: keyserver.ubuntu.com
  - type: apt
    url: https://dl.winehq.org/wine-builds/ubuntu/
    suites: [jammy]
    components: [main]
    architectures: [amd64, i386]
    key-id: D43F640145369C51D786DDEA76F1A20FF987672F

parts:
  extensible-hooks:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-utils-library.git
    source-subdir: snapcraft-assets/extensible-hooks

  ld-precache:
    after:
      - extensible-hooks
      - gnome-extension-hack
      - lutris
      - lutris-runtime
      - tools
      - vulkan
      - winehacks
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-utils-library.git
    source-subdir: snapcraft-assets/ld-precache

  enable-i386:
    plugin: nil
    override-pull: |
      craftctl default
      dpkg --add-architecture i386
      apt update

  gnome-extension-hack:
    plugin: dump
    source: .
    override-pull: |
      cat <<'EOF' > gnome-extension-hack
      #!/bin/sh
      set +x
      rm -f "$XDG_DATA_HOME/icons/hicolor/"* || true
      if [ "$SNAP_ARCH" = "amd64" ]; then
        export LD_LIBRARY_PATH="$SNAP/usr/lib/i386-linux-gnu:$SNAP/lib/i386-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib"

        export LIBGL_DRIVERS_PATH="$LIBGL_DRIVERS_PATH:$SNAP/usr/lib/i386-linux-gnu/dri"
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LIBGL_DRIVERS_PATH"
        export LIBVA_DRIVERS_PATH="$SNAP/usr/lib/i386-linux-gnu/dri"

        # For some reason LD_PRELOAD ends up borked with an unexpanded $LIB on `bindtextdomain.so`,
        # since this is in the gnome SDK it's x86_64, and there doesn't appear to be an i386 available in the
        # snap at all so we're just gonna void the whole thing
        unset LD_PRELOAD
      fi
      export XDG_DATA_HOME="$SNAP_USER_COMMON/.local/share"
      # Force i386
      export SNAP_ARCH=i386
      export ARCH="i386-linux-gnu"
      export SNAP_LAUNCHER_ARCH_TRIPLET="$ARCH"

      # Gnome extension breaks fontconfig atm, this will cause wine to break in a very subtle
      # way that's only clear if you compare verbose wine logs with one without the issue (the
      # wine server will start freaking out while adding windows CJK fonts to the registry)
      unset FONTCONFIG_FILE
      unset FONTCONFIG_PATH

      exec "$@"
      EOF
      chmod +x gnome-extension-hack
    organize:
      gnome-extension-hack: bin/gnome-extension-hack

  lutris:
    after: [enable-i386]
    plugin: meson
    source: .
    parse-info: [usr/share/metainfo/net.lutris.Lutris.metainfo.xml]
    meson-parameters:
      - --prefix=/usr
    stage-packages:
      - python3-distro
      - python3-pil
      - python3-lxml
      - python3-requests
      - python3-yaml
      - libmagic1
    override-pull: |
      craftctl default
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/lutris.svg|' share/applications/net.lutris.Lutris.desktop
    prime:
      - -usr/lib/*/libharfbuzz*

  lutris-runtime:
    after: [enable-i386]
    plugin: nil
    override-pull: |
      craftctl default
      dpkg --add-architecture i386
      apt update
    stage-packages:
      - cabextract
      - curl
      - fluid-soundfont-gs
      - libgnutls30
      - libgl1
      - libxrandr2
      - p7zip-full
      - psmisc
      - unzip
      - wine
      - xz-utils
      - x11-xserver-utils
      #32 bit
      - lib32gcc-s1
      - libc6-i386
      - libgl1:i386
      - libglu1-mesa:i386
      - libglvnd0:i386
      - libglx-mesa0:i386
      - libgnutls30:i386
      - libvulkan1:i386
      - libx11-6:i386
    stage:
      - -lib/ld-linux.so.2
      - -usr/bin/cpp-7
      - -usr/lib/*/libjavascript*
      - -usr/lib/*/libwebkit*
      - -usr/share/doc/cpp/README.Debian
      - -usr/share/man/man1/cpp-7.1.gz
    build-attributes:
      - no-patchelf

  vulkan:
    plugin: nil
    stage-packages:
      - mesa-vulkan-drivers
    prime:
      - usr/bin/mesa-overlay-control.py
      - usr/lib/*/libVkLayer*
      - usr/lib/*/libvulkan*
      - usr/lib/*/libxcb-randr*
      - usr/lib/*/libLLVM*
      - usr/share/drirc.d
      - usr/share/vulkan

  # So basically without this `/usr/lib/i386-linux-gnu/` doesn't contain `ld-linux.so.2`
  # which causes an absolutely *inscrutable* error loading any version of `wine`. The executable
  # is limited to a one line error message with gives "no such file or directory" seemingly pointing to itself,
  # this actually *means* it can't find `ld-linux.so.2` which exists as a symlink in `/usr/lib` but without its matching
  # referant.
  #
  # This hack is stolen from the Steam snap and basically forces the `i386` stuff to properly exist.
  #
  # The only other real option is to use `patchelf` to patch any wine to find a bundled `ld-linux.so.2` and
  # matching `glibc`, but since Lutris downloads a bespoke wine for almost every game, that would be rather
  # annoying and probably kind of fragile.
  winehacks:
    plugin: nil
    stage-packages:
      - winehq-stable
    build-snaps: [core22]
    override-prime: |
      craftctl default
      set -eux
      cp -a /snap/core22/current/usr/lib/i386-linux-gnu/* usr/lib/i386-linux-gnu/

  tools:
    plugin: nil
    stage-packages:
      - vulkan-tools
      - mesa-utils
      - pciutils
      - winetricks
    prime:
      - usr/lib/*/libpci*
      - usr/bin/glxgears*
      - usr/bin/glxinfo*
      - usr/bin/vkcube
      - usr/bin/vkcubepp
      - usr/bin/lspci
      - usr/bin/winetricks
      - usr/share/icons/hicolor/scalable/apps

hooks:
  install:
    command-chain:
      - bin/gnome-extension-hack
  post-refresh:
    command-chain:
      - bin/gnome-extension-hack

layout:
  /usr/lib/p7zip:
    bind: $SNAP/usr/lib/p7zip
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /usr/share/lutris:
    bind: $SNAP/usr/share/lutris
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm
  /usr/lib/i386-linux-gnu:
    bind: $SNAP/usr/lib/i386-linux-gnu
  /usr/lib/x86_64-linux-gnu/dri:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/dri
  /usr/share/glvnd/egl_vendor.d:
    bind: $SNAP/usr/share/glvnd/egl_vendor.d
  /usr/lib/x86_64-linux-gnu/alsa-lib:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/vulkan:
    bind: $SNAP/usr/share/vulkan
  /usr/lib/x86_64-linux-gnu/libvulkan_intel.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_intel.so
  /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
  /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
  /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
  /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0.0.0
  /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
  /usr/lib/x86_64-linux-gnu/libxcb.so:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
  /usr/lib/x86_64-linux-gnu/libxcb.so.1:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0

slots:
  dbus-lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris

  nvidia-client:
    interface: dbus
    bus: system
    name: nvidia.powerd.client

plugs:
  # No interface provides these, need to be added to something
  # (probably the `opengl` plug).
  nvidia-driver-version:
    interface: system-files
    read:
      - /proc/driver/nvidia/version
      - /proc/driver/nvidia/gpus

  shmem:
    interface: shared-memory
    private: true

  # Needed because Lutris attempts to directly control its children
  # via `/proc` (e.g. `/proc/<pid>/environ` and `/proc/<pid>/tasks/<pid>/children`)
  # but no current interface allows this. This should probably be added to
  # `process-control` or `system-monitor`.
  all-of-proc-do-not-enable-this:
    interface: system-files
    read:
      - /proc

environment:
  HOME: $SNAP_USER_COMMON
  # Export Vulkan ICD filename paths
  VK_ICD_FILENAMES: /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json

apps:
  lutris:
    command-chain: [bin/gnome-extension-hack]
    command: usr/bin/lutris -d
    extensions: [gnome]
    desktop: usr/share/applications/net.lutris.Lutris.desktop
    common-id: net.lutris.Lutris
    plugs:
      - all-of-proc-do-not-enable-this
      - audio-playback
      - avahi-control
      - avahi-observe
      - browser-support
      - daemon-notify
      - desktop
      - desktop-legacy
      - gsettings
      - hardware-observe
      - home
      - shmem
      - system-observe
      - io-ports-control
      - introspect
      - joystick
      - kvm
      - libvirt
      - mount-observe
      - network
      - network-bind
      - network-manager
      - nvidia-driver-version
      - opengl
      - process-control
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - system-trace
      - unity7
      - udisks2
      - wayland
      - x11
    slots:
      - dbus-lutris
      - nvidia-client
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      PATH: /usr/bin:$SNAP/usr/lib/wine:$PATH
      MAGIC: $SNAP/usr/share/misc/magic.mgc

  vkcube:
    extensions: [gnome]
    command: usr/bin/vkcube
  glxinfo:
    extensions: [gnome]
    command: usr/bin/glxinfo
  glxgears:
    extensions: [gnome]
    command: usr/bin/glxgears
  # wine:
  #   extensions: [gnome-3-28]
  #   command: usr/bin/wine-stable

  # wine64:
  #   extensions: [gnome-3-28]
  #   command: usr/bin/wine64-stable

  # winecfg:
  #   extensions: [gnome-3-28]
  #   command: usr/bin/winecfg-stable
